spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/test1
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true #띄어쓰기 8칸
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true

